travis:
  secure:
    BINSTAR_TOKEN: T9M8R6RaZh03RN26mHA/lmWsgCRzbOkzmmHw1yCrPgoLyBXRgzf15IzoUjvdq3WDPImJgoOfGDbs+cnARXEeOp55gFeDlUgOt7mGxgendx/K4Qd0yE2itF+T0n+p98ITBT24DD9ufBeL4hmMBTyuc+3I+KIlXo44uXWFkQP4hIHb9pYnBU8x0ZVk+W1G3MY7LdAKbOoqqto3Dy9ijF6OEqZ/+lrCO8NWFfLNhgy3WGO8aooBrygc4xpfXcOjMtd+5XXzfy41HrSt2bOQiirQUdHLrDmtBZe2G4RfX2MdOk70AHH+6CauDBD0ymB3AuHKzVknIeQejhwHfTHHAUQtY0L1fuAGJbY09bHMlen+3OfWCfAilRk4PixUVopkG3g4NQmTQMRGT0HeuC0s1TZD3v+Har769ewkRGlcvZ3eRu1N2yXI8xgFoCfoVg0QbvH581PQ8/tbC5HaumbXrW0x/t2btBaDvncAUFVeEGByZSxB1xZCVK4daggX91g8dE/aM3V0EyQIOoSWOGxIeIJ2CMMk9xcnCdvO1vkadCtSG74H7dWm9X5En3wwMs4nWfyYx0c2sLqhwurglc+/Ehx4I9RIrz7XG9eMIDbEiT9wqqGYeqOFCpMfCKpw+9osrZ5/Odopy7k3XJx1ZNouoXgOHwTxxsNlB4l4nG3qgdpKgGc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
