travis:
  secure:
    BINSTAR_TOKEN: klvwA9WVC/YVXzNGn1m9aUeYUn2tlPh+invk6D0N+RefxBoa9oSDB9Q3BOA9ZizVJ+CoXBrNIOHRwGbRTBnnNHczMDNikCsBs80LFLj/E+Z7UeLGYy0edmYE4jJMdgDxTzJN/ff0Ny+qf5SJIAwAV7d+51guJ1N1eh181IAs2eJvXUtj1Gj2xnkGdAbQ3MyiUf0TxuAsWUB9BLSUzF+d/l+9qEb6xAE30vd2xZOYXwJ/vPCyuS0u/4jqxC9JkfNv2QbkQzw8xBKWb9LxzjV2W7cYnxG2X1olBKkNwNnZgYSRHjOaxt4Zgvs8qSPAqo4TEkF7eqMNeWqNEmpG85ANTnCgcrCWWQfXW7XE7ougY/5k5S1vxnBOZpnIxSBFTtPrluOGWv8zS4WmZm1FTL5zAlTNp04fCSwkKjjqLIi0pBD15EUqUACNFMumuvfw52WK+OCFqnsF7rAfxO/l/0nE+1YdxJCrneybcQJjRIPsGocRywdh54FoEgoRueaiJ58jhAp8FzcBYTOY91zXLCYrgs+ivLP612/iKFypfxlh1l07sJnHQTRMK7X9lPOYmoNEUrpLH1k8TjDtsXLZhgbJtrVoAfeKvDBXqDByVle6E2G4DHxIxyvpd+HPb2aFevml8QyihOJ6rnEnveK+YTWpBl1p7i9LwIHmwVicS94Z7HI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
